export enum TABS {
  ALL = "ALL",
  //
  POST = "POST",
  EVENT = "EVENT",
  NEWS = "NEWS",
  SHARING = "SHARING",
  NOTIFICATION = "NOTIFICATION",
  RECRUITMENT = "RECRUITMENT",
  RESOURCE = "RESOURCE",
  REQUEST = "REQUEST",
  ROOM = "ROOM",
  DEVICE = "DEVICE",
  FURNITURE = "FURNITURE",
  OTHER = "OTHER",
}
